var express = require('express')
var multer = require('multer')
var router = express.Router()
var userCtrl = require('../controllers/users/usersCtrl')
var eventCtrl = require('../controllers/users/eventCtrl')
var playlistCtrl = require('../controllers/users/playlistCtrl')
var creditCtrl = require('../controllers/users/creditCtrl')
var songsCtrl = require('../controllers/users/songsCtrl')
var favCtrl = require('../controllers/users/favCtrl')
var paymentCtrl = require('../controllers/users/paymentCtrl')


router.post('/login',userCtrl.login)
router.post('/logout',userCtrl.logout)
router.post('/register',userCtrl.register)
router.post('/info',userCtrl.info)
router.post('/social',userCtrl.social)
router.post('/confirm',userCtrl.confirm)
router.post('/change-password',userCtrl.changePassword)
router.post('/forget-password',userCtrl.forgetPassword)
router.post('/change-recover-password',userCtrl.changeRecoverPassword)
router.post('/update-profile',multer({'dest':'./uploads/'}).any(),userCtrl.updateProfile)
router.post('/update-lat-long',userCtrl.updateLatLong)
router.post('/events',eventCtrl.all)
router.post('/event',eventCtrl.details)
router.post('/playlists',playlistCtrl.getAll)
router.post('/playlist/songs',playlistCtrl.songs)
router.post('/credits',creditCtrl.get)
router.post('/credits/add',creditCtrl.add)
router.post('/requested',songsCtrl.getAll)
router.post('/song/request',songsCtrl.request)
router.post('/fav/add', favCtrl.add)
router.post('/fav/remove', favCtrl.remove)
router.post('/favs', favCtrl.list)
router.post('/addpromo',creditCtrl.addPromo)
router.post('/genre',userCtrl.genre)
router.post('/create',paymentCtrl.create)
router.post('/addcard',paymentCtrl.addcard)
router.post('/listcards',paymentCtrl.listcards)
router.post('/deletecard',paymentCtrl.deletecard)
router.post('/updatecard',paymentCtrl.updatecard)




module.exports = router
